export * from './About'
export * from './Services'
export * from './Contact'
export * from './Home'
export * from './Portfolio'
export * from './Privacy'
export * from './Terms'
export * from './Internship'
